# Generated by Django 5.2 on 2025-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience', models.TextField()),
            ],
        ),
    ]
