# Generated by Django 5.2 on 2025-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_petsitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('referent', models.CharField(max_length=100, verbose_name='Référent animal')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
