# Generated by Django 5.2 on 2025-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_company_delete_petsitter_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='maladie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
