# Generated by Django 5.2 on 2025-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_created_at_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(default='Non spécifiée', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='maladie',
            field=models.CharField(blank=True, default='Aucune maladie connue', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
