# Generated by Django 5.2 on 2025-04-23 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companybooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSitterCompanyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('formation', 'Formation spécialisée'), ('consultation', 'Consultation professionnelle'), ('collaboration', "Collaboration pour garde d'animaux")], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('finished', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_petsitter_bookings', to=settings.AUTH_USER_MODEL)),
                ('petsitter', models.ForeignKey(limit_choices_to={'role': 'petsitter'}, on_delete=django.db.models.deletion.CASCADE, related_name='petsitter_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
