# Generated by Django 5.2 on 2025-04-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_petsittercompanybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('finished', 'Terminée'), ('cancelled', 'Annulée'), ('paid', 'Payée')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=10)),
                ('payment_type', models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('transfer', 'Virement bancaire')], default='card', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.booking')),
                ('company_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.companybooking')),
            ],
        ),
    ]
