# Generated by Django 5.2 on 2025-04-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_booking_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('paid', 'Payée')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='companybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='petsittercompanybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=10),
        ),
    ]
