# Generated by Django 5.2 on 2025-05-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_animal_animal_type_alter_companybooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybooking',
            name='company_paid',
            field=models.BooleanField(default=False),
        ),
    ]
