# Generated by Django 5.2 on 2025-05-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_companybooking_company_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='maladie',
            field=models.CharField(blank=True, default='No known illnesses', max_length=200, null=True),
        ),
    ]
